PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?count ?description
WHERE {
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P2101 [] . BIND("Total number of chemicals with a melting point" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P2102 [] . BIND("Total number of chemicals with a boiling point" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P1117 [] . BIND("Total number of chemicals with a pKa" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P231 [] . BIND("Total number of CAS registry numbers" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P235 [] . BIND("Total number of InChIKeys" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P3636 | wdt:P11375 [] . BIND("Total number of chemicals with crystal structures" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P6689 [] . BIND("Total number of chemicals with mass spectra" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P9405 [] . BIND("Total number of chemicals with NMR spectra" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P2201 [] . BIND("Total number of chemicals with a electronic dipole moment" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P2260 [] . BIND("Total number of chemicals with a ionization potential" AS ?description)
    } GROUP BY ?description
  }
  UNION
  {
    SELECT (COUNT(*) AS ?count) ?description WHERE {
      [] wdt:P4952 [] . BIND("Total number of chemicals with a safety classification and labelling" AS ?description)
    } GROUP BY ?description
  }
}
ORDER BY DESC(?count)
